services:
  frontend:
    container_name: dockerized-react
    build: ./frontend/
    ports: 
      - "3000:5173"
    
    volumes:
      - ./frontend/:/app
      - /app/node_modules/

  db:
    container_name: mysql_db
    build: ./db/
    ports: 
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
